[package]
name = "hibari-brick-rs"
version = "0.1.0"
authors = ["Tatsuya Kawano <tatsuya@hibaridb.org>"]
build = "build.rs"

[build-dependencies]

[dependencies]
byteorder = "0.5.3"
lazy_static = "0.2.1"
promising-future = "0.2.4"
rmp-serialize = "0.7.0"
rocksdb = "0.3.5"
rust-crypto = "0.2.36"
rustc-serialize = "0.3.19"

clippy = { version = "*", optional = true }
