[package]
name = "hibari-brick-rs"
version = "0.1.0"
authors = ["Tatsuya Kawano <tatsuya@hibaridb.org>"]
build = "build.rs"

[build-dependencies]

[dependencies]
blake2-rfc = "0.2.17"
byteorder = "1.0.0"
data-encoding = "2.0.0-rc.1"
lazy_static = "0.2.2"
promising-future = "0.2.4"
rmp-serde = "0.13.1"
rocksdb = "0.6.0"
serde = "1.0.7"
serde_derive = "1.0.7"

clippy = { version = "*", optional = true }
