[package]
name = "hibari-brick-rs"
version = "0.1.0"
authors = ["Tatsuya Kawano <tatsuya@hibaridb.org>"]
build = "build.rs"

[build-dependencies]

[dependencies]
byteorder = "1.0.0"
# chrono = "0.2"
chrono = "0.3.1"
lazy_static = "0.2.2"
promising-future = "0.2.4"
rand = "0.3.15"
rmp-serialize = "0.8.0"
rocksdb = "0.6.0"
rust-crypto = "0.2.36"
rustc-serialize = "0.3.22"
# timer = "0.1.4"
timer = { git = "https://github.com/alexbool/timer.rs" }

clippy = { version = "*", optional = true }
